# Generated by Django 5.2.7 on 2026-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('college', 'Teacher'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
